[colors.bright]
black = "0x707680"
blue = "0x5C80B0"
cyan = "0x6CE0EB"
green = "0x98C398"
magenta = "0xD5A2EB"
red = "0xE47C87"
white = "0xFFFFFF"
yellow = "0xD1BB79"

[colors.normal]
black = "0x40444C"
blue = "0x3A5C91"
cyan = "0x56B6C2"
green = "0x82A882"
magenta = "0xC187E0"
red = "0xD06C75"
white = "0xE0E0E0"
yellow = "0xC0A36F"

[colors.primary]
background = "0xF9F9F9"
foreground = "0x363A40"

[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[[hints.enabled]]
command = "/usr/bin/garcon-url-handler"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control|Shift"

[window]
opacity = 1
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 10
y = 10

[keyboard]
